name: Default Toolbar Button Hide Sort
id: default_toolbar_button_hide_sort
key: default_toolbar_button_hide_sort
author_link: http://www.tinybeans.net/blog/
author_name: Tomohiro Okuwaki
description: This is used with "Default Toolbar Button Hide Plugin".
version: 2.0
plugin_link: http://www.tinybeans.net/blog/download/mt-plugin/default-toolbar-button-hide.html

buttons:
    dtbh_inline:
        face_text: Sort
        title: This is used with "Default Toolbar Button Hide Plugin".
        code: |
            function ceb_dtbh_inline ( text ) {
                var formatting = jQuery("div.field-buttons-formatting");
                if (formatting.css("float") == "left") {
                    formatting.css({"float":"none","padding-right":0});
                } else {
                    formatting.css({"float":"left","padding-right":"4px"});
                }
            }
